server:
  port: 8000

spring:
  application:
    name: apigateway-service
#  cloud:
#    gateway:
#      routes:
#        - id: user-service
#          uri: http://localhost:8081/
#          predicates:
#            - Path=/api/user-service/**
#        - id: board-service
#          uri: http://localhost:8082/
#          predicates:
#            - Path=/api/board-service/**

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
